### ISSUE TITLE
Short-term roadmap for this implementation 

### ISSUE THREAD

**Issue by waynexia** [datafusion-contrib/datafusion-orc#7]
Previous discussion: https://github.com/apache/arrow-datafusion/issues/4707

Though the ORC format is not as widely used as parquet in arrow-rs and datafusion related projects, there are still some (growing, to my feelings) interesting and requirements on this format. As @Jefffrey said [here](https://github.com/apache/arrow-datafusion/issues/4707#issuecomment-1792031298), a noticeable and viable milestone for this project is it can be merged into arrow-rs. This draft roadmap is raised to help us discuss, arrange and take our efforts toward that milestone.

Given the ORC format is less complex than parquet, there are still many work to do in various aspects. Here is a list of functionalities need to be done if we consider making ORC files queriable from datafusion as the primary use case on this stage. Please feel free to add/remove/set priorities to them. It's likely that we can't finish all of them in a short term, thus marking what are going to be done is also important.

- [ ] primitive data types
- [ ] common compress methods
- [ ] user metadata
 

And belows are also related but with lower priorities
- [ ] encryption
- [ ] compond data types
- [ ] index

Then something I'm not sure about. Looking for more information. Also feel free to change previous two lists.
- [ ] other encodings
- [ ] file metadata and statistics

**Comment by Jefffrey** [comment]
Thanks for writing this here.

Just to preface, I'm no expert in ORC nor do I technically have a usecase for it, so can take my thoughts with a grain of salt. With that said:

- Encryption can probably be placed lowest priority, probably into the longer-term roadmap. Even parquet in arrow-rs doesn't yet support encryption
- We can probably bump the encodings to highest priority. I assume you're referring to the V1 encodings, which should be simpler to implement than V2 which seems to already be present
- I haven't looked into statistics and indexes much, but they do seem important for stuff like predicate pushdown, so can be medium priority or so

I'll create more issues based on this roadmap

**Comment by alamb** [comment]
BTW some potentially relevant documents in case anyone is interested:

[A Deep Dive into Common Open Formats for Analytical](https://www.vldb.org/pvldb/vol16/p3044-liu.pdf)

[An Empirical Evaluation of Columnar Storage Formats](https://arxiv.org/pdf/2304.05028.pdf)

**Comment by Jefffrey** [comment]
> BTW some potentially relevant documents in case anyone is interested:
> 
> [A Deep Dive into Common Open Formats for Analytical](https://www.vldb.org/pvldb/vol16/p3044-liu.pdf)
> 
> [An Empirical Evaluation of Columnar Storage Formats](https://arxiv.org/pdf/2304.05028.pdf)

Thanks for these, will definitely give a read!

**Comment by klangner** [comment]
What is missing from this roadmap which is required to allow this library be added to the datafusion (and arrow-rs, polars?)
I would be interested in helping with this effort as we have orc files which we would like to query.

**Comment by Jefffrey** [comment]
hey @klangner thanks for the interest!

For DataFusion there is an issue for it: https://github.com/datafusion-contrib/datafusion-orc/issues/63

Right now it lacks support for projection, not to mention the code is sequestered in an example instead of being code as part of the library.

For arrow-rs it's basically just... all features needed for supporting read use cases (sorry if this is too vague :sweat_smile: )

I'm not familiar with polars so I can't say on that front.

For now I'm imagining enhancing the API for RecordBatch reading (akin to what parquet provides in arrow-rs) and also creating the necessary impl's to allow DataFusion to read from ORC files using this library.
